language: csharp
dotnet: 2.1.803
os: linux
dist: bionic
mono: latest
sudo: required

install:
before_script:
script:
- dotnet build -c Release
- dotnet test test/Bitfinex.Client.Websocket.Tests -c Release
deploy:
  provider: script
  skip_cleanup: true
  script:
    - cd src/Bitfinex.Client.Websocket && dotnet pack /p:PackageVersion=4.1.$TRAVIS_BUILD_NUMBER -c Release && cd bin/Release && dotnet nuget push **/*.4.1.$TRAVIS_BUILD_NUMBER.nupkg -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
  on:
    branch: master